version: '3'
services:

  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
    #   - POSTGRES_DB=cr
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASS=postgres
    #   - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=cr
      - POSTGRES_USER=suite5
      - POSTGRES_PASS=suite5
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
    #   - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,fuzzystrmatch
    #   CREATE EXTENSION fuzzystrmatch;
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  dbbackups:
    image: kartoza/pg-backup:11.0
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    links:
      - db:db
    environment:
      - DUMPPREFIX=childr
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=cr
      - PGPORT=5432
      - PGHOST=db
    restart: on-failure
    depends_on:
        - db

  child_rescue_development:
    env_file: ../../Backend/.env
    build:
      context: ../../
      dockerfile: server/develop/Dockerfile
    volumes:
      - media:/home/docker/persistent/media
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
        - db
    container_name: child-rescue-dev

volumes:
  dbbackups:
  postgis-data:
  media:











#volumes:
#  database:
#    driver: local


#  postgres:
#    restart: always
#    image: postgres
#    environment:
#        - POSTGRES_USER='postgres'
#        - POSTGRES_PASSWORD='postgres'
#        - POSTGRES_DB='cr'
#    ports:
#        - '5432:5432'
#    volumes:
#        - database:/var/lib/postgresql/data


#  postgres:
#    restart: 'always'
#    ports:
#        - '5432:5432'
#    environment:
#        - "FILLA_DB_USER=suite5"
#        - "FILLA_DB_PASSWORD=suite5"
#        - "FILLA_DB_DATABASE=cr"
#        - "POSTGRES_PASSWORD=password"
#    build: './database'
#    expose:
#        - "5432"
#    volumes:
#        - database:/var/lib/postgresql/data
