# Generated by Django 2.1.5 on 2019-12-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alert_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="custom_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
