# Generated by Django 2.1.5 on 2019-12-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alert_custom_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="alert", name="custom_name",),
    ]
