# Generated by Django 2.2.8 on 2020-11-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_remove_alert_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='volunteers_only',
            field=models.BooleanField(default=False),
        ),
    ]
