# Generated by Django 2.1.5 on 2019-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auto_20191029_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization", name="created_at", field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(model_name="organization", name="updated_at", field=models.DateTimeField(auto_now=True),),
    ]
