# Generated by Django 2.1.5 on 2019-12-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20191029_1606"),
    ]

    operations = [
        migrations.RemoveField(model_name="organization", name="website",),
    ]
