# Generated by Django 2.2.8 on 2019-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_remove_organization_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.CharField(blank=True, max_length=4056, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="facebook",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="how_to_become_volunteer",
            field=models.CharField(blank=True, max_length=4056, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="instagram",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="missing_child_actions",
            field=models.CharField(blank=True, max_length=4056, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="twitter",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
