# Generated by Django 2.2.8 on 2020-11-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20191218_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
