# Generated by Django 2.1.5 on 2019-02-18 09:31

import core.evidences.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='photo',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.evidences.utils.evidence_image_path),
        ),
    ]
