# Generated by Django 2.1.5 on 2019-02-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0002_auto_20190218_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='user',
        ),
    ]
