# Generated by Django 2.1.5 on 2019-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="radius",),
        migrations.AlterField(
            model_name="place", name="description", field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
