# Generated by Django 2.1.5 on 2019-11-26 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20191126_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Feedback'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
