# Generated by Django 2.2.8 on 2020-01-21 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_place_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
