# Generated by Django 2.2.8 on 2020-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_is_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='radius',
            field=models.FloatField(default=0.1),
        ),
    ]
