# Generated by Django 2.2.8 on 2020-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200521_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.CharField(choices=[('asylum_related', 'Hosting Facility/Asylum related'), ('romance_related', 'Romance related'), ('health_related', 'Hospital/Health related'), ('transport_related', 'Public Transport related'), ('isolation_related', 'Rural/Forest/Isolated Area'), ('streets_related', 'On The Streets'), ('social_related', 'Social Event/Amusement Place'), ('hobby_related', 'Hobby related'), ('family_related', 'Family/Relatives/Friend property'), ('education_related', 'Education/Sports related'), ('probable_destination', 'Probable destination'), ('checked_in', 'Checked-in recently/multiply'), ('social_event', 'Social event'), ('fact', 'Fact'), ('other', 'Other/Unknown')], default='other', max_length=128),
        ),
    ]
