# Generated by Django 2.2.8 on 2020-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200522_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tag',
            field=models.CharField(choices=[('asylum_related', 'Hosting Facility/Asylum related'), ('romance_related', 'Romance related'), ('health_related', 'Hospital/Health related'), ('transport_related', 'Public Transport related'), ('isolation_related', 'Rural/Forest/Isolated Area'), ('streets_related', 'On The Streets'), ('social_related', 'Social Event/Amusement Place'), ('family_related', 'Family/Relatives/Friend property'), ('education_related', 'Education/Sports related'), ('other', 'Other/Unknown')], default='other', max_length=128),
        ),
    ]
