# Generated by Django 2.1.5 on 2019-03-01 14:25

import core.alerts.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('radius', models.FloatField(default=5.0)),
                ('type', models.CharField(blank=True, choices=[('amber', 'Amber alert'), ('alert', 'Alert')], max_length=20, null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=1024)),
                ('disappearance_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=256, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.alerts.utils.image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
    ]
