# Generated by Django 2.1.5 on 2019-04-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='end_timestamp',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='start_timestamp',
            new_name='start',
        ),
    ]
