# Generated by Django 2.1.5 on 2019-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20190405_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
