# Generated by Django 2.1.5 on 2019-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20190408_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
