# Generated by Django 2.1.5 on 2019-04-08 09:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20190408_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='geolocation_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
