# Generated by Django 2.1.5 on 2019-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20190408_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
