# Generated by Django 2.1.5 on 2019-07-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0001_initial"), ("firebase", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="fcmdevice",
            name="uuid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device",
                to="users.Uuid",
            ),
        )
    ]
