# Generated by Django 2.1.5 on 2019-04-04 12:56

import core.cases.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=254, null=True)),
                ('has_mobile_phone', models.BooleanField(default=False)),
                ('has_money_or_credit', models.BooleanField(default=False)),
                ('has_area_knowledge', models.BooleanField(default=False)),
                ('rescue_teams_utilized', models.BooleanField(default=False)),
                ('volunteers_utilized', models.BooleanField(default=False)),
                ('organizations_cooperated', models.IntegerField(blank=True, null=True)),
                ('transit_country', models.CharField(blank=True, max_length=1000, null=True)),
                ('disappearance_type', models.CharField(blank=True, choices=[('runaway', 'Runaway'), ('parental', 'Parental'), ('abduction', 'Abduction'), ('criminal', 'Criminal'), ('missing', 'Missing'), ('minor', 'Minor'), ('tracing', 'Tracing'), ('request', 'Request'), ('unclear', 'Unclear')], max_length=20, null=True)),
                ('multi_times_case', models.IntegerField(blank=True, null=True)),
                ('probable_destinations', models.CharField(blank=True, max_length=5000, null=True)),
                ('clothing_with_scent', models.BooleanField(default=False)),
                ('amber_alert', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'cases',
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'children',
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('home_country', models.CharField(blank=True, max_length=250, null=True)),
                ('home_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('home_city', models.CharField(blank=True, max_length=256, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=256, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('first_grade', '1st Grade'), ('second_grade', '2st Grade'), ('third_grade', '3st Grade'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('languages_spoken', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('arrival_at_facility_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'demographic_data',
                'db_table': 'demographic_data',
            },
        ),
        migrations.CreateModel(
            name='FacilityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField()),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facility_history',
            },
        ),
        migrations.CreateModel(
            name='FacilityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField()),
                ('is_present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facility_report',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'db_table': 'case_follower',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.cases.utils.CaseUtils.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_issues', models.CharField(blank=True, choices=[('pathological', 'Pathological'), ('other', 'Other')], max_length=30, null=True)),
                ('medical_treatment_required', models.BooleanField(default=False)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'medical_data',
                'db_table': 'medical_data',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('father_fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_mother', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_father', models.CharField(blank=True, max_length=15, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'personal_data',
                'db_table': 'personal_data',
            },
        ),
        migrations.CreateModel(
            name='PhysicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eye_color', models.CharField(blank=True, choices=[('blue', 'Blue'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('other', 'other')], max_length=20, null=True)),
                ('hair_color', models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('red', 'Red'), ('blonde', 'Blonde'), ('other', 'other')], max_length=20, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('stature', models.CharField(blank=True, choices=[('tall', 'Tall'), ('short', 'Short'), ('normal', 'Normal')], max_length=20, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('fat', 'Fat'), ('slim', 'Slim'), ('normal', 'Normal')], max_length=20, null=True)),
                ('characteristics', models.CharField(blank=True, max_length=5000, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_data', to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'physical_data',
                'db_table': 'physical_data',
            },
        ),
        migrations.CreateModel(
            name='PsychologicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media', models.CharField(blank=True, max_length=2048, null=True)),
                ('concerns', models.CharField(blank=True, choices=[('child_headed_household', 'Child headed household'), ('disabled', 'Disabled'), ('medical_case', 'Medical case'), ('street_child', 'Street child')], max_length=30, null=True)),
                ('personality', models.CharField(blank=True, choices=[('antisocial', 'Antisocial'), ('suicidal', 'Suicidal'), ('autistic', 'Autistic'), ('depressive', 'Depressive')], max_length=30, null=True)),
                ('family', models.CharField(blank=True, choices=[('both_parents', 'Both parents'), ('mother', 'Mother'), ('father', 'Father'), ('no_parents', 'No parents')], max_length=30, null=True)),
                ('mothers_profile', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('sufficient', 'Sufficient'), ('not_good', 'Not good'), ('really_bad', 'Really bad'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('fathers_profile', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('sufficient', 'Sufficient'), ('not_good', 'Not good'), ('really_bad', 'Really bad'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('school_absences', models.CharField(blank=True, max_length=2048, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=2048, null=True)),
                ('relationship_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=50, null=True)),
                ('religion', models.CharField(blank=True, choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=50, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychological_data', to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'psychological_data',
                'db_table': 'psychological_data',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_platform_app', models.CharField(blank=True, max_length=500, null=True)),
                ('social_account', models.CharField(blank=True, max_length=500, null=True)),
                ('social_preferences', models.CharField(blank=True, max_length=500, null=True)),
                ('social_activity', models.CharField(blank=True, max_length=500, null=True)),
                ('social_network', models.CharField(blank=True, max_length=500, null=True)),
                ('social_checkins', models.CharField(blank=True, max_length=500, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_data', to='cases.Case')),
            ],
            options={
                'verbose_name_plural': 'social_media_data',
                'db_table': 'social_media_data',
            },
        ),
    ]
