# Generated by Django 2.1.5 on 2019-02-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='physicaldata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_data', to='cases.Case'),
        ),
    ]
