# Generated by Django 2.1.5 on 2019-04-19 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('facilities', '0001_initial'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityreport',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='facilityreport',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facility'),
        ),
        migrations.AddField(
            model_name='facilityhistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
        migrations.AddField(
            model_name='facilityhistory',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facility'),
        ),
        migrations.AddField(
            model_name='demographicdata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_data', to='cases.Case'),
        ),
        migrations.AddField(
            model_name='case',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Child'),
        ),
        migrations.AddField(
            model_name='case',
            name='facility',
            field=models.ManyToManyField(through='cases.FacilityHistory', to='facilities.Facility'),
        ),
        migrations.AddField(
            model_name='case',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
