# Generated by Django 2.1.5 on 2019-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190404_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='default_message',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
