# Generated by Django 2.1.5 on 2019-02-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190218_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.Child'),
        ),
    ]
