# Generated by Django 2.1.5 on 2019-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190218_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Child'),
        ),
        migrations.AlterField(
            model_name='physicaldata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='socialdata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_data', to='cases.Case'),
        ),
    ]
