# Generated by Django 2.1.5 on 2019-04-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20190409_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_data', to='cases.Case'),
        ),
    ]
