# Generated by Django 2.1.5 on 2019-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20190409_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaldata',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('red', 'Red'), ('blond', 'Blond'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
