# Generated by Django 2.1.5 on 2019-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20190410_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='health_issues_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='health_issues',
            field=models.CharField(blank=True, choices=[('pathological', 'Pathological'), ('diabetes', 'Diabetes'), ('heart_issues', 'Heart Issues'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
