# Generated by Django 2.1.5 on 2019-04-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_psychologicaldata_school_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicaldata',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_account',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_activity',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_checkins',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_network',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_platform_app',
        ),
        migrations.RemoveField(
            model_name='socialmediadata',
            name='social_preferences',
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='has_social_profiles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='psychologicaldata',
            name='school_absences',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('none', 'None'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
