# Generated by Django 2.1.5 on 2019-04-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20190410_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='multi_times_case',
        ),
    ]
