# Generated by Django 2.1.5 on 2019-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='conditions_of_disappearance',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='family_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='latitude_of_disappearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='longitude_of_disappearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='multi_times_case',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='probable_destinations',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='reasons_of_disappearance',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='transit_country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
