# Generated by Django 2.1.5 on 2019-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0002_auto_20190722_1024")]

    operations = [
        migrations.AlterField(
            model_name="demographicdata",
            name="arrival_at_facility_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demographicdata",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
