# Generated by Django 2.1.5 on 2019-08-07 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0003_auto_20190722_1433"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follower", unique_together={("user", "case")}
        )
    ]
