# Generated by Django 2.1.5 on 2019-08-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0004_auto_20190807_0911")]

    operations = [
        migrations.RemoveField(model_name="personaldata", name="mobile"),
        migrations.RemoveField(model_name="personaldata", name="mobile_father"),
        migrations.RemoveField(model_name="personaldata", name="mobile_mother"),
    ]
