# Generated by Django 2.1.5 on 2019-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0005_auto_20190807_1213")]

    operations = [
        migrations.RemoveField(model_name="psychologicaldata", name="fathers_profile"),
        migrations.RemoveField(model_name="psychologicaldata", name="mothers_profile"),
        migrations.AddField(
            model_name="medicaldata",
            name="triggered_event",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="psychologicaldata",
            name="addiction",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="psychologicaldata",
            name="disappearance_reasons",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="psychologicaldata",
            name="parents_profile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="disappearance_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="demographicdata",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_grade", "1st Grade"),
                    ("second_grade", "2st Grade"),
                    ("third_grade", "3st Grade"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="demographicdata",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="medical_treatment_required",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="concerns",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="family",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="personality",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_relationship", "In a relationship"),
                    ("complicated", "It's complicated"),
                    ("broke_up", "Recently broke up"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="religion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="school_absences",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("none", "None"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
