# Generated by Django 2.1.5 on 2019-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0007_auto_20190808_1335")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_present",
            field=models.BooleanField(blank=True, null=True),
        )
    ]
