# Generated by Django 2.1.5 on 2019-09-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0008_case_is_present")]

    operations = [
        migrations.AlterField(
            model_name="case", name="is_present", field=models.NullBooleanField()
        )
    ]
