# Generated by Django 2.1.5 on 2019-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0009_auto_20190903_0843")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="current_facility_id",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
