# Generated by Django 2.1.5 on 2019-10-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0011_case_presence_status")]

    operations = [migrations.RemoveField(model_name="case", name="current_facility_id")]
