# Generated by Django 2.1.5 on 2019-10-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0012_remove_case_current_facility_id")]

    operations = [migrations.RemoveField(model_name="case", name="is_present")]
