# Generated by Django 2.1.5 on 2019-11-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_feed_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
    ]
