# Generated by Django 2.1.5 on 2019-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_remove_feed_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="presence_status",
            field=models.CharField(
                blank=True,
                choices=[("present", "Present"), ("not_present", "Not present"), ("transit", "Transit")],
                default="present",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="tag",
            field=models.CharField(
                choices=[("announcement", "Announcement"), ("task", "Task"), ("fact", "Fact"), ("general", "General")],
                default="general",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="medicaldata",
            name="health_issues",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pathological", "Pathological"),
                    ("diabetes", "Diabetes"),
                    ("heart_issues", "Heart Issues"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="body_type",
            field=models.CharField(
                blank=True, choices=[("fat", "Fat"), ("slim", "Slim"), ("normal", "Normal")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="eye_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blue", "Blue"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("other", "other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="hair_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("brown", "Brown"),
                    ("red", "Red"),
                    ("blond", "Blond"),
                    ("other", "other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="skin_color",
            field=models.CharField(
                blank=True,
                choices=[("white", "White"), ("brown", "Brown"), ("dark", "Dark"), ("other", "other")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="stature",
            field=models.CharField(
                blank=True,
                choices=[("tall", "Tall"), ("short", "Short"), ("normal", "Normal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_relationship", "In a relationship"),
                    ("complicated", "It's complicated"),
                    ("broke_up", "Recently broke up"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="school_absences",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("none", "None")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="psychologicaldata",
            name="school_grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("average", "Sufficient"),
                    ("not_good", "Not good"),
                    ("bad", "Bad"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
