# Generated by Django 2.1.5 on 2019-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_auto_20191129_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicaldata",
            name="eye_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="hair_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="physicaldata",
            name="skin_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light_pale", "Light Pale"),
                    ("pale", "Pale"),
                    ("tanned", "Tanned"),
                    ("brown", "Brown"),
                    ("dark_brown", "Dark Brown"),
                    ("black", "Black"),
                    ("unknown", "Unknown"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
