# Generated by Django 2.1.5 on 2019-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_auto_20191203_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="is_visible_to_volunteers",
            field=models.BooleanField(default=False),
        ),
    ]
