# Generated by Django 2.1.5 on 2019-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_feed_is_visible_to_volunteers"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="custom_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
