# Generated by Django 2.1.5 on 2019-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0030_auto_20191212_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="blockchain_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="languages_spoken",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
