# Generated by Django 2.2.8 on 2019-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_socialnetworksdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="clothing_with_scent",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="has_area_knowledge",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="has_mobile_phone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("deactivated", "Yes but deactivated or otherwise untrackable"),
                    ("abductor", "Yes the abductor"),
                    ("no", "No"),
                    (None, "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="has_money_or_credit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("probably_yes", "Probably Yes"),
                    ("probably_no", "Probably No"),
                    ("no", "No"),
                    (None, "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
