# Generated by Django 2.2.8 on 2020-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0033_auto_20191220_1600"),
    ]

    operations = [
        migrations.AddField(model_name="case", name="end_date", field=models.DateField(blank=True, null=True),),
    ]
