# Generated by Django 2.2.8 on 2020-01-21 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0034_case_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case", name="data", field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
