# Generated by Django 2.2.8 on 2020-05-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_auto_20200430_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='concerns',
            field=models.CharField(blank=True, choices=[('neglect', 'Neglect'), ('parent_relation', 'Relation with the parents'), ('parent_separation', 'Recent separation of parents'), ('on_migration', 'On Migration'), ('parents_in_dispute', 'Parents in dispute (at court or otherwise)'), ('physical_sexual_abuse', 'Domestic violence/Sexual abuse'), ('death_of_family_member', 'Recent death of family member/friend'), ('possibly', 'Possibly'), ('none', 'None'), (None, 'Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='disappearance_reasons',
            field=models.CharField(blank=True, choices=[('family_issues', 'Family Issues'), ('personal_issues', 'Personal Issues/Bullying'), ('love_affair', 'Love affair'), ('health_issues', 'Health issues'), ('mass_disaster', 'Mass disaster'), ('migration', 'Migration/In search for relatives'), ('other', 'Other'), (None, 'Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('illegal', 'No papers/Illegal'), ('temp_papers', 'Temporal papers'), ('asylum_granted', 'Asylum granted'), ('asylum_applied', 'Asylum Seeker/Applicant'), ('legal', 'Legal/Asylum granted'), (None, 'Other/Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='living_environment',
            field=models.CharField(blank=True, choices=[('divorced_parents', 'Divorced parents'), ('single_bio_parent', 'Single parent family'), ('both_bio_parents', 'Living with both biological parents'), ('bio_step_parents', 'Mixed (biological and step parents)'), ('camp', 'Living in open accommodation facility (e.g. camp)'), ('facility', 'Living in camp/hosting facility'), ('relatives', 'Living with relatives/foster family'), ('institution', 'Living in closed institution / hosting facility'), ('transit', 'In transit'), (None, 'Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='mental_disorders',
            field=models.CharField(blank=True, choices=[('possibly', 'Possibly'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe, self-threatening'), ('none', 'None'), (None, 'Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='psychological_disorders',
            field=models.CharField(blank=True, choices=[('possibly', 'Possibly'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe, self-threatening'), ('none', 'None'), (None, 'Unknown')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('in_relationship', 'In a relationship'), ('complicated', "It's complicated"), ('broke_up', 'Recently broke up'), ('other', 'Other'), (None, 'Other/Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='school_grades',
            field=models.CharField(blank=True, choices=[('not_attending', 'Not Attending School'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Sufficient'), ('not_good', 'Not good'), ('bad', 'Bad'), (None, 'Unknown')], max_length=50, null=True),
        ),
    ]
