# Generated by Django 2.2.8 on 2020-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_auto_20200522_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('illegal', 'No papers/Illegal'), ('asylum_applied', 'Asylum Seeker/Applicant'), ('legal', 'Legal/Asylum granted'), (None, 'Other/Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('in_relationship', 'In a relationship'), ('complicated', "It's complicated"), ('broke_up', 'Recently broke up'), (None, 'Other/Unknown')], max_length=50, null=True),
        ),
    ]
