# Generated by Django 2.2.8 on 2020-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_auto_20200612_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='body_type',
            field=models.CharField(blank=True, choices=[('petit', 'Petit'), ('slim', 'Slim'), ('normal', 'Normal'), ('overweight', 'Overweight'), ('corpulent', 'Corpulent'), (None, 'Unknown')], max_length=20, null=True),
        ),
    ]
