# Generated by Django 2.2.8 on 2020-07-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_auto_20200702_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
