# Generated by Django 2.2.8 on 2020-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_sharedcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="addiction",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case", name="birth_country", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="body_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("petit", "Petit"),
                    ("slim", "Slim"),
                    ("normal", "Normal"),
                    ("overweight", "Overweight"),
                    ("corpulent", "Corpulent"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="concerns",
            field=models.CharField(
                blank=True,
                choices=[
                    ("neglect", "Neglect"),
                    ("parent_relation", "Relation with the parents"),
                    ("parent_separation", "Recent separation of parents"),
                    ("on_migration", "On Migration"),
                    ("parents_in_dispute", "Parents in dispute (at court or otherwise)"),
                    ("physical_sexual_abuse", "Domestic violence/Sexual abuse"),
                    ("death_of_family_member", "Recent death of family member/friend"),
                    ("possibly", "Possibly"),
                    ("none", "None"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="disappearance_reasons",
            field=models.CharField(
                blank=True,
                choices=[
                    ("family_issues", "Family Issues"),
                    ("personal_issues", "Personal Issues/Bullying"),
                    ("love_affair", "Love affair"),
                    ("health_issues", "Health issues"),
                    ("mass_disaster", "Mass disaster"),
                    ("migration", "Migration/In search for relatives"),
                    ("other", "Other"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="disappearance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("runaway", "Runaway"),
                    ("parental_abduction", "Parental Abduction"),
                    ("lost", "Lost, injured or otherwise missing"),
                    ("missing", "Missing UAM"),
                    ("third_party_abduction", "Third-party Abduction"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_grade", "1st Grade"),
                    ("second_grade", "2st Grade"),
                    ("third_grade", "3st Grade"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case", name="eye_color", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case", name="hair_color", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case", name="haircut", field=models.CharField(blank=True, max_length=22560, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="has_trafficking_history",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("possibly", "Possibly"), ("no", "No"), (None, "Unknown")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="health_issues",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case", name="home_address", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case", name="home_country", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_first_time_missing",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_high_risk",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("possibly", "Possibly"), ("no", "No"), (None, "Unknown")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_refugee",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case", name="languages_spoken", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="legal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("illegal", "No papers/Illegal"),
                    ("asylum_applied", "Asylum Seeker/Applicant"),
                    ("legal", "Legal/Asylum granted"),
                    (None, "Other/Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="living_environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("divorced_parents", "Divorced parents"),
                    ("single_bio_parent", "Single parent family"),
                    ("both_bio_parents", "Living with both biological parents"),
                    ("bio_step_parents", "Mixed (biological and step parents)"),
                    ("camp", "Living in open accommodation facility (e.g. camp)"),
                    ("facility", "Living in camp/hosting facility"),
                    ("relatives", "Living with relatives/foster family"),
                    ("institution", "Living in closed institution / hosting facility"),
                    ("transit", "In transit"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="medical_treatment_required",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="mental_disorders",
            field=models.CharField(
                blank=True,
                choices=[
                    ("possibly", "Possibly"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe, self-threatening"),
                    ("none", "None"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="parents_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father_step_father", "Father/Stepfather"),
                    ("mother_stepmother", "Mother/Stepmother"),
                    ("both", "Both"),
                    ("none", "None"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="physical_disabilities",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="psychological_disorders",
            field=models.CharField(
                blank=True,
                choices=[
                    ("possibly", "Possibly"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe, self-threatening"),
                    ("none", "None"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_relationship", "In a relationship"),
                    ("complicated", "It's complicated"),
                    ("broke_up", "Recently broke up"),
                    (None, "Other/Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case", name="religion", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="school_grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_attending", "Not Attending School"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("average", "Sufficient"),
                    ("not_good", "Not good"),
                    ("bad", "Bad"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="skin_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light_pale", "Light Pale"),
                    ("pale", "Pale"),
                    ("tanned", "Tanned"),
                    ("brown", "Brown"),
                    ("dark_brown", "Dark Brown"),
                    ("black", "Black"),
                    (None, "Unknown"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="stature",
            field=models.CharField(
                blank=True,
                choices=[("tall", "Tall"), ("short", "Short"), ("normal", "Normal"), (None, "Unknown")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="triggered_event",
            field=models.CharField(
                blank=True, choices=[("yes", "Yes"), ("no", "No"), (None, "Unknown")], max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="child", name="father_fullname", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="child", name="first_name", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="child", name="full_name", field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), (None, "Unknown")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="child", name="last_name", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="child", name="mother_fullname", field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
