# Generated by Django 2.1.5 on 2019-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191101_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('coordinator', 'Coordinator'), ('organization_manager', 'Organization Manager'), ('case_manager', 'Case Manager'), ('network_manager', 'Network Manager'), ('facility_manager', 'Facility Manager'), ('volunteer', 'Volunteer'), ('simple_user', 'Simple User')], max_length=20),
        ),
    ]
