# Generated by Django 2.1.5 on 2019-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20191101_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
