# Generated by Django 2.1.5 on 2019-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191101_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_leader',
            field=models.NullBooleanField(default=False),
        ),
    ]
