# Generated by Django 2.1.5 on 2019-11-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_is_team_leader"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_team_leader",),
    ]
