# Generated by Django 2.1.5 on 2019-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedbacks", "0002_auto_20190722_1024")]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="child_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="transportation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
