# Generated by Django 2.1.5 on 2019-09-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("feedbacks", "0003_auto_20190808_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.Organization",
            ),
        )
    ]
