# Generated by Django 2.1.5 on 2019-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0004_feedback_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback", name="score", field=models.FloatField(default=0.0),
        ),
    ]
