# Generated by Django 2.1.5 on 2019-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0006_feedback_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="note",
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
